# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        P6\UserBundle\Entity\User: plaintext
        
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
              entity:
                class:    P6\UserBundle\Entity\User
                property: username

    role_hierarchy:
                # Un admin hérite des droits d'auteur et de modérateur
                ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
                # On garde ce rôle superadmin, il nous resservira par la suite
                ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
              login_path: login
              check_path: login_check
            logout:
              path: logout
              target: /

    access_control:
        - { path: ^/delete, roles: ROLE_ADMIN }


            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
