<?php

namespace P6\PlatformBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTricksLimited()
    {


        $queryBuilder = $this->createQueryBuilder("category")
            ->where("category.trick = :trick")
            ->setParameter("category", $category);
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
