<?php

use Doctrine\ORM\EntityRepository;

namespace P6\PlatformBundle\Repository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory($category)
    {
        $queryBuilder = $this->createQueryBuilder("t")
            ->where("t.category = :category")
            ->setParameter("category", $category);
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;

    }
}
